version: '3'

services:
  shark:
    image: shark:1
    environment:
      - MONGO_USERNAME=test
      - MONGO_PASSWORD=test
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=test
    command: ./wait-for.sh mongodb:27017 -- node ./app.js
    ports:
      - "1234:8080"
    restart: always

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    logging:
      driver: none
    ports:
      - "26977:27017"
    volumes:
      - mongodb:/data/db
    command: --wiredTigerCacheSizeGB 6
    restart: always

volumes:
  mongodb:
  kubectl run kubia --image=luksa/kubia --port=8080 --generator=run/v1 запуск имеджа + rc
  kubectl expose rc kubia --type=LoadBalancer --name kubia-http добавления к нашему имеджу лоадбалансера
  kubectl explain pods для вывода описания манифеста для пода
  kubectl get po kubia-manual -o yaml описание пода девопс
  kubectl get po --show-labels с метками
  kubectl get po -L creation_method,env с конкретными метками
  kubectl label po kubia-manual creation_method=manual дать метку меток
  kubectl label po kubia-manual-v2 env=debug --overwrite изменить метку
  kubectl get po -l creation_method=manual вывести под с конкретной меткой
  kubectl get po -l env вывести с любым значением метки или же не имеют такую метку '!env'
  kubectl get svc --all-namespaces посмотреть во всех нэймспэсах
  kubectl delete po -l rel=canary удаление всех подов с конкретными метками